-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 14:45:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb(EAD)
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb(EAD)` ;

-- -----------------------------------------------------
-- Schema mydb(EAD)
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb(EAD)` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb(EAD)` ;

-- -----------------------------------------------------
-- Table `mydb(EAD)`.`diet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`diet` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`diet` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Type` (`Type` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb(EAD)`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`actor` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`actor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Caregiver_ID` INT NULL DEFAULT NULL,
  `Diet_ID` INT NULL DEFAULT NULL,
  `NameGiven` VARCHAR(40) NOT NULL,
  `NameFamily` VARCHAR(40) NULL DEFAULT NULL,
  `AddressEmail` VARCHAR(40) NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `Role` VARCHAR(10) NOT NULL,
  `Type` VARCHAR(10) NULL DEFAULT NULL,
  `Contact` VARCHAR(10) NOT NULL,
  `AddressStreet` VARCHAR(255) NOT NULL,
  `AddressUnit` VARCHAR(10) NULL DEFAULT NULL,
  `AddressPostal` VARCHAR(6) NOT NULL,
  `AddressLongX` DECIMAL(10,6) NOT NULL,
  `AddressLatY` DECIMAL(10,6) NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `Note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `AddressEmail` (`AddressEmail` ASC) VISIBLE,
  INDEX `Caregiver_ID` (`Caregiver_ID` ASC) VISIBLE,
  INDEX `Diet_ID` (`Diet_ID` ASC) VISIBLE,
  CONSTRAINT `actor_ibfk_1`
    FOREIGN KEY (`Caregiver_ID`)
    REFERENCES `mydb(EAD)`.`actor` (`ID`),
  CONSTRAINT `actor_ibfk_2`
    FOREIGN KEY (`Diet_ID`)
    REFERENCES `mydb(EAD)`.`diet` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb(EAD)`.`sysparameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`sysparameter` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`sysparameter` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Purpose` VARCHAR(40) NOT NULL,
  `Value` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Purpose` (`Purpose` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb(EAD)`.`mealplan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`mealplan` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`mealplan` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FSP_ID` INT NOT NULL,
  `Diet_ID` INT NOT NULL,
  `Sequence` INT NOT NULL,
  `Meal` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `FSP_ID` (`FSP_ID` ASC, `Diet_ID` ASC, `Sequence` ASC) VISIBLE,
  INDEX `Diet_ID` (`Diet_ID` ASC) VISIBLE,
  CONSTRAINT `mealplan_ibfk_1`
    FOREIGN KEY (`FSP_ID`)
    REFERENCES `mydb(EAD)`.`actor` (`ID`),
  CONSTRAINT `mealplan_ibfk_2`
    FOREIGN KEY (`Diet_ID`)
    REFERENCES `mydb(EAD)`.`diet` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb(EAD)`.`ingredientplan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`ingredientplan` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`ingredientplan` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MealPlan_ID` INT NOT NULL,
  `Ingredient` VARCHAR(40) NOT NULL,
  `Quantity` INT NOT NULL,
  `UOM` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Ingredient` (`Ingredient` ASC, `MealPlan_ID` ASC) VISIBLE,
  INDEX `MealPlan_ID` (`MealPlan_ID` ASC) VISIBLE,
  CONSTRAINT `ingredientplan_ibfk_1`
    FOREIGN KEY (`MealPlan_ID`)
    REFERENCES `mydb(EAD)`.`mealplan` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb(EAD)`.`mealprep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`mealprep` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`mealprep` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FSP_ID` INT NOT NULL,
  `Diet_ID` INT NOT NULL,
  `Sequence` INT NOT NULL,
  `Meal` VARCHAR(40) NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `DateTimeOpened` DATETIME NOT NULL,
  `DateTimeSup` DATETIME NULL DEFAULT NULL,
  `DateTimePrep` DATETIME NULL DEFAULT NULL,
  `DateTimeClosed` DATETIME NULL DEFAULT NULL,
  `RatingMeal` INT NULL DEFAULT NULL,
  `FeedbackMeal` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `FSP_ID` (`FSP_ID` ASC, `Diet_ID` ASC, `Sequence` ASC) VISIBLE,
  INDEX `Diet_ID` (`Diet_ID` ASC) VISIBLE,
  CONSTRAINT `mealprep_ibfk_1`
    FOREIGN KEY (`FSP_ID`)
    REFERENCES `mydb(EAD)`.`actor` (`ID`),
  CONSTRAINT `mealprep_ibfk_2`
    FOREIGN KEY (`Diet_ID`)
    REFERENCES `mydb(EAD)`.`diet` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb(EAD)`.`ingredientprep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`ingredientprep` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`ingredientprep` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MealPrep_ID` INT NOT NULL,
  `Ingredient` VARCHAR(40) NOT NULL,
  `Quantity` INT NOT NULL,
  `UOM` VARCHAR(10) NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Ingredient` (`Ingredient` ASC, `MealPrep_ID` ASC) VISIBLE,
  INDEX `MealPrep_ID` (`MealPrep_ID` ASC) VISIBLE,
  CONSTRAINT `ingredientprep_ibfk_1`
    FOREIGN KEY (`MealPrep_ID`)
    REFERENCES `mydb(EAD)`.`mealprep` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb(EAD)`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb(EAD)`.`delivery` ;

CREATE TABLE IF NOT EXISTS `mydb(EAD)`.`delivery` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MealPrep_ID` INT NOT NULL,
  `Rider_ID` INT NOT NULL,
  `Member_ID` INT NOT NULL,
  `MealState` VARCHAR(10) NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `DateTimeOpened` DATETIME NOT NULL,
  `DateTimeClosed` DATETIME NULL DEFAULT NULL,
  `RatingDelivery` INT NULL DEFAULT NULL,
  `FeedbackDelivery` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `MealPrep_ID` (`MealPrep_ID` ASC) VISIBLE,
  INDEX `Rider_ID` (`Rider_ID` ASC) VISIBLE,
  INDEX `Member_ID` (`Member_ID` ASC) VISIBLE,
  CONSTRAINT `delivery_ibfk_1`
    FOREIGN KEY (`MealPrep_ID`)
    REFERENCES `mydb(EAD)`.`mealprep` (`ID`),
  CONSTRAINT `delivery_ibfk_2`
    FOREIGN KEY (`Rider_ID`)
    REFERENCES `mydb(EAD)`.`actor` (`ID`),
  CONSTRAINT `delivery_ibfk_3`
    FOREIGN KEY (`Member_ID`)
    REFERENCES `mydb(EAD)`.`actor` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
